version: '2'

services:

  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  php:
    depends_on:
      - mysql
      - themes
      - plugins
      - uploads
    build: ./docker/php-fpm
    container_name: php
    environment:
      - WP_INSTALLATION_TYPE
    volumes:
      - "./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini"
      - "./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
      - "./docker/wordpress/wp-config.php:/var/www/public/wp-config.php"
      - "./docker/wordpress/object-cache.php:/var/www/public/wp-content/object-cache.php"
      - "public:/var/www/public"
    volumes_from:
      - themes
      - plugins
      - uploads
    links:
      - mysql
      - memcached
      - mailhog
      - themes
      - plugins

  nginx:
    depends_on:
      - php
    ports:
      - "8080:80"
    image: nginx:latest
    container_name: nginx
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    volumes_from:
      - php
    links:
      - php
    restart: always

  memcached:
    image: phpdockerio/memcached:latest
    container_name: memcached

  mailhog:
    image: phpdockerio/mailhog:latest
    container_name: mailhog
    ports:
      - "8081:8025"

  themes:
    build: ./docker/wordpress
    container_name: themes
    volumes:
      - "./code/themes:/var/www/public/wp-content/themes"

  plugins:
    build: ./docker/wordpress
    container_name: plugins
    volumes:
      - "./code/plugins:/var/www/public/wp-content/plugins"

  uploads:
    build: ./docker/wordpress
    container_name: uploads
    volumes:
      - "./code/uploads:/var/www/public/wp-content/uploads"

  vip:
    build: ./docker/wordpress/vip
    container_name: vip
    volumes: 
      - "vip:/var/www/public/wp-content/mu-plugins"

volumes:
  public:
  vip: