version: '2'

services:

  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  phpfpm:
    depends_on:
      - mysql
      - code
    build: ./docker/php-fpm
    container_name: phpfpm
    volumes:
      - "./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini"
      - "./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
    volumes_from:
      - code
    links:
      - mysql
      - memcached
      - mailhog
      - code

  nginx:
    depends_on:
      - phpfpm
    ports:
      - "8080:80"
    image: nginx:latest
    container_name: nginx
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    links:
      - phpfpm
    restart: always

  memcached:
    image: phpdockerio/memcached:latest
    container_name: memcached

  mailhog:
    image: phpdockerio/mailhog:latest
    container_name: mailhog
    ports:
      - "8081:8025"

  code:
    build: ./docker/wordpress
    container_name: code
    volumes:
      - "./code:/var/www/public/"